spring.application.name=sql-lite
spring.datasource.url=jdbc:sqlite:file::memory:?cache=shared&transaction_mode=deferred
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.hibernate.ddl-auto=create-drop

# Connection pool settings for SQLite with 50 concurrent users
spring.datasource.hikari.maximum-pool-size=6
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.idle-timeout=600000
spring.datasource.hikari.max-lifetime=1800000

# Thread Pool Configuration
app.read.thread.pool.size=5
app.write.thread.pool.size=1

# Transaction Configuration
spring.transaction.default-timeout=30s

## Connection pool settings for SQLite with 5 concurrent users
#spring.datasource.hikari.maximum-pool-size=1
#spring.datasource.hikari.minimum-idle=2
#spring.datasource.hikari.connection-timeout=30000
#spring.datasource.hikari.idle-timeout=30000
#spring.datasource.hikari.max-lifetime=600000

# Use the shared memory mode for SQLite
#spring.datasource.url=jdbc:sqlite:file::memory:?cache=shared

# Enable WAL
#spring.datasource.hikari.connection-init-sql=PRAGMA journal_mode=WAL; PRAGMA synchronous=NORMAL; PRAGMA busy_timeout=30000;

#spring.datasource.url=jdbc:sqlite:file::memory:?cache=shared&busy_timeout=30000
#spring.datasource.hikari.connection-init-sql=PRAGMA journal_mode=WAL; PRAGMA synchronous=NORMAL; PRAGMA locking_mode=NORMAL;


# Batch Configuration
spring.jpa.properties.hibernate.jdbc.batch_size=10
spring.jpa.properties.hibernate.order_inserts=true
spring.jpa.properties.hibernate.order_updates=true
spring.jpa.properties.hibernate.batch_versioned_data=true

# Enable statistics to see batch operations
spring.jpa.properties.hibernate.generate_statistics=true
logging.level.org.hibernate.stat=debug
logging.level.org.hibernate.engine.jdbc.batch.internal.BatchingBatch=TRACE
logging.level.org.hibernate.engine.jdbc.spi.SqlExceptionHelper=TRACE